SELECT DISTINCT t.ITEM_ID, i.ITEM_NAME, i.RARITY
FROM ITEM_INFO parent
JOIN ITEM_TREE t ON parent.ITEM_ID = t.PARENT_ITEM_ID
JOIN ITEM_INFO i ON t.ITEM_ID = i.ITEM_ID
WHERE parent.RARITY = 'RARE'
ORDER BY t.ITEM_ID DESC;